---
# Общие переменные продуктива
domain: corp.crmfactory.local
dns_servers:
  - 10.10.30.11   # будущий внутренний DNS (временно)
  - 77.88.8.8     # Yandex.DNS — РФ-устойчивый внешний
ntp_servers:
  - ntp1.vniiftri.ru
  - ntp2.vniiftri.ru
timezone: Europe/Moscow

# Мониторинг: агенты на всё
zabbix_server_host: 10.10.30.11
glpi_agent_server: http://10.10.30.12

# Telegram-алерты (токен — из OpenBao, НЕ коммитить)
telegram_bot_token: "{{ lookup('env', 'TG_BOT_TOKEN') | default('') }}"
telegram_chat_id: "{{ lookup('env', 'TG_CHAT_ID') | default('') }}"

# Пароль БД Zabbix — из env/OpenBao
zabbix_db_password: "{{ lookup('env', 'ZABBIX_DB_PASSWORD') | default('changeme') }}"
